-- DELETE FROM users;

-- TRUNCATE TABLE users RESTART IDENTITY;
-- TRUNCATE TABLE login RESTART IDENTITY;

-- DROP TABLE users;
-- DROP TABLE login;

DELETE FROM users WHERE id = 8;
DELETE FROM login WHERE id = 8;
